# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Runs Tests on Push

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1 
        with:
            persist-credentials: false

      - name: Build 
        run: npm build

      - name: Linting
        run: npm run lint:test --if-present
        env:
           CI: true

      - name: Run unit tests
        run: npm run test --if-present
        env:
           CI: true
